//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHelloClientProxy.MyHelloNamespace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:www-infosupport-com:KC:Demos", ConfigurationName="MyHelloNamespace.IHello", CallbackContract=typeof(MyHelloClientProxy.MyHelloNamespace.IHelloCallback))]
    public interface IHello {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:www-infosupport-com:KC:Demos/IHello/SayHello")]
        void SayHello(string prompt);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:www-infosupport-com:KC:Demos/IHello/SayHello")]
        System.Threading.Tasks.Task SayHelloAsync(string prompt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:www-infosupport-com:KC:Demos/IHello/SayHelloBack")]
        void SayHelloBack(string result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloChannel : MyHelloClientProxy.MyHelloNamespace.IHello, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloClient : System.ServiceModel.DuplexClientBase<MyHelloClientProxy.MyHelloNamespace.IHello>, MyHelloClientProxy.MyHelloNamespace.IHello {
        
        public HelloClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public HelloClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public HelloClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public HelloClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public HelloClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SayHello(string prompt) {
            base.Channel.SayHello(prompt);
        }
        
        public System.Threading.Tasks.Task SayHelloAsync(string prompt) {
            return base.Channel.SayHelloAsync(prompt);
        }
    }
}
